stages:         
  - build
variables:
    DEVELOPER_DIR: /Applications/Xcode-15.0.0.app

default: 
  tags: 
    - xcode15

build SDK:     
  stage: build
  script:
    - xcodebuild -scheme StreamDeckKit -destination 'platform=iOS Simulator,OS=17.0,name=iPad Pro (11-inch) (4th generation)' -sdk iphonesimulator17.0

build Simulator:     
  stage: build
  script:
    - xcodebuild -scheme StreamDeckSimulator -destination 'platform=iOS Simulator,OS=17.0,name=iPad Pro (11-inch) (4th generation)' -sdk iphonesimulator17.0