name: "Run Tests"
run-name: Testing
on: [pull_request]
jobs:
  Test:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Test StreamDeckKit
        run: set -o pipefail && xcodebuild -scheme StreamDeckKit-Package test -destination "platform=iOS Simulator,name=iPhone 15,OS=latest" -skipMacroValidation | xcpretty
